Desktop version
DamenaM/setup-and-mobile-first-project pull request #8
Opened 2022-12-16 15:08 UTC by DamenaM

### PR Desktop Version

- [ ] adding desktop version
- [ ] adding a contact form 
- [ ] adding cards  
- [ ] adding media queries

2022-12-16 15:12 UTC, anagudelogu reviewed
Hi @DamenaM , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the correct README template. Please use the [updated version](https://github.com/microverseinc/readme-template) and submit your project again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-16 16:20 UTC, amejid reviewed
Hi @DamenaM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the correct README template. Please use the [updated version](https://github.com/microverseinc/readme-template) and submit your project again. The only optional section is the `FAQ` section. The table of contents should also be present.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-16 19:50 UTC, huseyinbiyik requested changes
Hi @DamenaM,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Linter checks passing 🟢
- GitHub flow followed 📂


## Required Changes ♻️
- Kindly use media queries and flexbox to have a responsive web page. Check the gif below and notice that your page is not responding for different screen sizes. All sections have responsivity problems right now. Kindly fix that. 

![desktop](https://user-images.githubusercontent.com/25887253/208177196-0532af00-8a59-4db5-9e97-dd5ce5f6073e.gif)

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 19:50 UTC, huseyinbiyik commented on style.css
> +@media screen and (min-width: 376px) {
Kindly use media query min-width: 768 to the desktop view. Right now, you have no breakpoints for the desktop. And please fix the overflow issue occurring on mobile view. Please check the gif below.
![mobile](https://user-images.githubusercontent.com/25887253/208170840-6c0885a2-bf4b-41e6-87ec-a12aaff8071c.gif)

2022-12-16 19:50 UTC, huseyinbiyik commented on index.html
> +          <a class="contact-desc" href="">Contact</a>
Please fix the font-style, size, color, font family and make sure you match the provided Figma design
Your design:
<img width="320" alt="Screenshot 2022-12-16 at 9 59 51 PM" src="https://user-images.githubusercontent.com/25887253/208171116-5d27981b-f81f-4311-935c-3a5e36cb4ef4.png">

Figma template:
<img width="564" alt="Screenshot 2022-12-16 at 10 10 27 PM" src="https://user-images.githubusercontent.com/25887253/208171477-d7e00c4c-6b12-408e-b412-3259566a7bdb.png">

2022-12-16 19:50 UTC, huseyinbiyik commented on index.html
>      <form class="cardcontact1" action="https://formspree.io/f/mwkzayzq" method="post" >
Kindly make sure your design matches the provided Figma template. Right now there is some alignment issues in both the heading and the paragraph. ↓
Figma template:
<img width="564" alt="Screenshot 2022-12-16 at 10 13 17 PM" src="https://user-images.githubusercontent.com/25887253/208171862-82e2668e-a567-49cf-b8df-d52b6663c619.png">
Your design:
<img width="831" alt="Screenshot 2022-12-16 at 10 01 54 PM" src="https://user-images.githubusercontent.com/25887253/208171980-c804c6e9-3138-43fd-a4e3-b5d9dce5bfc0.png">

2022-12-16 19:50 UTC, huseyinbiyik commented on index.html
>  <section class="cardcontact">
Kindly fix the gray area and try to follow the Figma template.
Figma template:
<img width="564" alt="Screenshot 2022-12-16 at 10 17 36 PM" src="https://user-images.githubusercontent.com/25887253/208172585-f3510e8a-7910-4668-83a6-40ca6cdaa981.png">
Your design:
<img width="1440" alt="Screenshot 2022-12-16 at 10 00 54 PM" src="https://user-images.githubusercontent.com/25887253/208172974-a51f77e4-6ab7-4bcb-8266-80ee2bd2d445.png">

2022-12-16 19:50 UTC, huseyinbiyik commented on index.html
> +            <div class="buttonsee2" id="contactbuttonid">
Please make sure you are following the Figma template for paddings, font-family, font-size, font color for the input element in the form. 
Figma template:
<img width="180" alt="Screenshot 2022-12-16 at 10 22 51 PM" src="https://user-images.githubusercontent.com/25887253/208173384-50574d24-42a2-4eb3-a7d0-7fd8a7ce6987.png">
Your design:
<img width="736" alt="Screenshot 2022-12-16 at 10 01 41 PM" src="https://user-images.githubusercontent.com/25887253/208173196-87af0f57-7dc3-4e29-9c77-bbdb0dbb9c40.png">

2022-12-16 19:50 UTC, huseyinbiyik commented on index.html
>                  <button class="contactbutton"> Get It Touch </button>
Kindly make sure if your submit button is aligned well like the provided design.
Your design:
<img width="1440" alt="Screenshot 2022-12-16 at 9 59 35 PM" src="https://user-images.githubusercontent.com/25887253/208173974-8d5dc84d-f62f-4537-bb11-2eed1ff4402b.png">
Figma template:
<img width="371" alt="Screenshot 2022-12-16 at 10 26 04 PM" src="https://user-images.githubusercontent.com/25887253/208173936-26c55bbd-d033-4f70-9106-3ed2a571159c.png">

2022-12-16 19:50 UTC, huseyinbiyik commented on index.html
>  <section class="gridcontainer">
Please make sure you add enough margin or padding to the right and left of the card according to the Figma design. 
Figma template:
<img width="803" alt="Screenshot 2022-12-16 at 9 58 42 PM" src="https://user-images.githubusercontent.com/25887253/208174659-67c9c7ca-bfbf-4865-85f9-c246120f84f6.png">

Your design:
<img width="1440" alt="Screenshot 2022-12-16 at 9 59 09 PM" src="https://user-images.githubusercontent.com/25887253/208174699-0fc25462-3b7c-4f92-a4df-79d612804c39.png">

2022-12-16 19:50 UTC, huseyinbiyik commented on index.html
> +<section class="AboutcardBack" id="aboutcardid">
Kindly fix the design and use flex and make sure your web page responding properly for different screen sizes. Right now, it seems About Myself self is just filling the half of its container.
Figma template:
<img width="674" alt="Screenshot 2022-12-16 at 10 00 30 PM" src="https://user-images.githubusercontent.com/25887253/208175399-ac78b597-d886-4a07-a3d8-be717d2b5022.png">

Your page:
<img width="1440" alt="Screenshot 2022-12-16 at 9 59 19 PM" src="https://user-images.githubusercontent.com/25887253/208175248-bf661c59-47d8-4458-8160-17d7cf51b0fc.png">

2022-12-17 16:13 UTC, levy002 approved these changes
## Hello @DamenaM 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-02 12:59 UTC, merged